APP-595 Convert healtcheck endpoint to actuator
symphonyoss/App-Integrations-Commons pull request #12
Opened 2017-01-17 17:08 UTC by rsanchez-daitan

- Include the 'spring-boot-actuator' dependency
- Created custom health indicators for applications

2017-01-18 12:16 UTC, miltongq approved these changes
Nice change making BaseIntegration implement Integration, the code is cleaner after this.
LGTM

2017-01-18 23:07 UTC, dnsymphony requested changes

2017-01-18 23:07 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/Integration.java
> +public interface Integration extends HealthIndicator {
Hmmm.  This forces everyone who implements Integration to have a dependency on Spring.  We should wrap the Spring classes in our own classes in public APIs (like this interface).

2017-01-19 12:55 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/Integration.java
> +public interface Integration extends HealthIndicator {
@dnsymphony Makes sense. I removed the dependency from HealthIndicator interface and created an adapter on integration-healthcheck module to get the health information from Integration interface and adapts to Health interface required by Spring Boot Actuator.

2017-01-19 12:55 UTC, rsanchez-daitan commented
@dnsymphony please check again.

2017-01-19 18:10 UTC, dnsymphony approved these changes

2017-01-19 18:31 UTC, merged