APP-1342-Incorrect status code on Integration Bridge Authorization API
symphonyoss/App-Integrations-Commons pull request #121
Opened 2017-10-17 11:58 UTC by Hamitay-Daitan

Added status code to OAuth1Exception

2017-10-17 15:34 UTC, campidelli requested changes

2017-10-17 15:34 UTC, campidelli commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/v1/OAuth1Exception.java
> +  private int code;
I don't think we should use HTTP codes here. There's the RemoteApiException for that.

2017-10-18 12:41 UTC, robson-sanchez approved these changes
LGTM

2017-10-18 15:51 UTC, campidelli approved these changes
LGTM

2017-10-18 15:54 UTC, merged