APP-1447: Integration Bridge needs support proxy server to connect to POD
symphonyoss/App-Integrations-Commons pull request #136
Opened 2017-11-24 13:32 UTC by Hamitay-Daitan

Added a proxy model and field to Integration Properties.
Fixed unit tests and added new ones based on the proxy model.

2017-11-24 14:50 UTC, crepache approved these changes
LGTM

2017-12-01 11:57 UTC, robson-sanchez requested changes

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-api-client/src/main/java/org/symphonyoss/integration/api/client/AppAuthenticationProxyApiClient.java
> +  String serviceName;
It should be a private field.

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-api-client/src/test/java/org/symphonyoss/integration/api/client/AppAuthenticationProxyApiClientTest.java
> +import org.slf4j.LoggerFactory;
This import is not required.

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/WebHookIntegration.java
> +        updateConfiguration(integrationUser);
Blank space?

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-api-client/src/main/java/org/symphonyoss/integration/api/client/SymphonyApiClient.java
> +import org.glassfish.jersey.client.ClientProperties;
This import is not required.

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/model/yaml/ConnectionInfo.java
> +  public void setProxyUser(String proxyUser) { this.proxy.setUser(proxyUser); }
Why do you set proxy info directly in this object?

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/model/yaml/IntegrationProperties.java
> +import java.util.List;
These imports are not being used.

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/model/yaml/IntegrationProperties.java
> +  public void setServices(Map<String, ConnectionInfo> services) { this.services = services; }
Should you override those service externally?

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/model/yaml/IntegrationProperties.java
> +  public Map<String, ConnectionInfo> getServices() { return services;  }
Should you export those services as a Map object? It should be better this method returns a list of services or you might provide a method to get service by id.

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-commons/src/test/java/org/symphonyoss/integration/model/yaml/ConnectionInfoTest.java
> +import java.net.URI;
This import is not used.

2017-12-01 11:57 UTC, rsanchez-daitan commented on integration-commons/src/test/java/org/symphonyoss/integration/model/yaml/ProxyConnectionInfoTest.java
> +    Assert.assertEquals(USER, proxy.getUser());
Please use the static import.

2017-12-01 13:07 UTC, robson-sanchez approved these changes

2017-12-01 13:08 UTC, merged