APP-908 Implement an engine to build the EntityJSON according to the metadata
symphonyoss/App-Integrations-Commons pull request #38
Opened 2017-03-31 17:04 UTC by rsanchez-daitan

- Helper class to retrieve Spring beans to be used for non-component classes

The 4 first commits are part of other PR's: #30, #33, and #35. If you want to review them first, I could rebase this PR after merging to reduce the number of files to be analyzed. Otherwise, I should close them.

2017-04-05 16:51 UTC, dnsymphony requested changes

2017-04-05 16:51 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/utils/ApplicationContextUtils.java
> +    throw new NoSuchBeanDefinitionException(type);
This should probably be IllegalStateException.

2017-04-05 16:51 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/utils/ApplicationContextUtils.java
> +    }
If context IS null, it should throw IllegalStateException

2017-04-05 16:51 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/utils/ApplicationContextUtils.java
> +public class ApplicationContextUtils {
This smells of bad design.  Why is it needed?  What non-Spring-managed classes need to access application context?

2017-04-05 16:51 UTC, dnsymphony commented on integration-commons/src/main/java/org/symphonyoss/integration/event/HealthCheckServiceEvent.java
> +public class HealthCheckServiceEvent {
What makes this an Event?  Same with the following class MessageMLVersionUpdatedEvent. They don't implement an Event interface.  They just seem to be wrapping a single field.

2017-04-10 14:04 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/event/HealthCheckServiceEvent.java
> +public class HealthCheckServiceEvent {
Renamed the classes to HealthCheckEventData and MessageMLVersionUpdatedEventData respectively.

2017-04-10 14:06 UTC, rsanchez-daitan commented on integration-commons/src/main/java/org/symphonyoss/integration/utils/ApplicationContextUtils.java
> +public class ApplicationContextUtils {
I agree with you @dnsymphony, it seems a bad design. I'm removing this class and refactoring the code was using this one.

2017-04-10 15:17 UTC, rsanchez-daitan commented
@dnsymphony please check again

2017-04-10 19:34 UTC, dnsymphony approved these changes

2017-04-11 12:54 UTC, merged