APP-624 Support MessageML v2
symphonyoss/App-Integrations-Commons pull request #44
Opened 2017-04-19 13:53 UTC by rsanchez-daitan

- Base parser class to generate MessageML v2 objects

2017-04-19 17:10 UTC, dnsymphony commented
Nice docs!

Lot's of new classes here, but no matching unit tests.

Does Travis report unit test coverage?

2017-04-19 19:57 UTC, rsanchez-daitan commented
@dnsymphony I'm not sure but I think Travis isn't reporting unit test coverage yet.

We need to check with Maurizio if it's required to configure some plugins on Maven to perform that report.

However, this PR has only the class MetadataParser with business logic. The other classes are only POJO to store the XML content. This class specifically has been tested.

2017-04-19 21:59 UTC, dnsymphony approved these changes

2017-04-19 22:09 UTC, dnsymphony requested changes

2017-04-19 22:09 UTC, dnsymphony commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +  protected abstract void preProcessInputData(JsonNode input);
This doesn't need to be abstract.  You can provide an implementation that does nothing.  That way if subclass doesn't need to do any pre-processing, it doesn't need to implement a do-nothing method.

2017-04-19 22:09 UTC, dnsymphony commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +  protected abstract void postProcessOutputData(EntityObject output, JsonNode input);
This doesn't need to be abstract. You can provide an implementation that does nothing. That way if subclass doesn't need to do any post-processing, it doesn't need to implement a do-nothing method.

2017-04-19 22:09 UTC, dnsymphony commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +   * This method must be implemented by the concrete parser classes to perform any data manipulation
This method _can_ be overridden...

2017-04-19 22:09 UTC, dnsymphony commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +   * This method must be implemented by the concrete parser classes to include additional fields
This method _can_ be overridden...

2017-04-19 22:23 UTC, rsanchez-daitan commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +   * This method must be implemented by the concrete parser classes to perform any data manipulation
DONE

2017-04-19 22:23 UTC, rsanchez-daitan commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +  protected abstract void preProcessInputData(JsonNode input);
DONE

2017-04-19 22:23 UTC, rsanchez-daitan commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +   * This method must be implemented by the concrete parser classes to include additional fields
DONE

2017-04-19 22:24 UTC, rsanchez-daitan commented on integration-webhook/src/main/java/org/symphonyoss/integration/webhook/parser/metadata/MetadataParser.java
> +  protected abstract void postProcessOutputData(EntityObject output, JsonNode input);
DONE

2017-04-20 04:20 UTC, maoo commented
@rsanchez-daitan @dnsymphony we can integrate with sonarqube in order to calculate testing coverage and other quality metrics; please read more on https://symphonyoss.atlassian.net/wiki/display/FM/Reporting#Reporting-SonarQube ; and - if interested - open an issue to request sonarqube to be enabled.

As an example, check the sonarqube dashboard of the symphony-java-client - https://sonarqube.com/dashboard?id=org.symphonyoss.symphony%3Asymphony-java-client

2017-04-24 22:37 UTC, rsanchez-daitan commented
@dnsymphony please check again

2017-04-24 22:59 UTC, dnsymphony approved these changes

2017-04-25 12:57 UTC, merged