APP-985 memory leak
symphonyoss/App-Integrations-Commons pull request #46
Opened 2017-04-21 21:07 UTC by ecarrenho-daitan

Due to memory leaks on the usage of Jersey client, we upgraded the Jersey version and also closed responses of Jersey requests.

2017-04-21 22:38 UTC, dnsymphony requested changes

2017-04-21 22:38 UTC, dnsymphony commented on integration-api-client/src/main/java/org/symphonyoss/integration/api/client/SimpleHttpApiClient.java
> -    return handleResponse(returnType, response);
It is an anti-pattern to open and close a resource in two different methods.  Put try/finally in each of these methods around the both lines (invoking request and handling response).

2017-04-24 21:17 UTC, ecarrenho-daitan commented on integration-api-client/src/main/java/org/symphonyoss/integration/api/client/SimpleHttpApiClient.java
> -    return handleResponse(returnType, response);
Done.

2017-04-24 22:27 UTC, dnsymphony approved these changes

2017-04-25 00:41 UTC, dnsymphony approved these changes

2017-04-26 02:47 UTC, merged