Meet 90% Unit Test Coverage on Commons Repo
symphonyoss/App-Integrations-Commons pull request #82
Opened 2017-06-23 14:35 UTC by crepache

Meet 90% Unit Test Coverage on Commons Repo

2017-06-23 14:54 UTC, campidelli requested changes

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/IntegrationRuntimeExceptionTest.java
> +        "Component: component\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/MissingConfigurationExceptionTest.java
> +    String expected = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/RemoteApiExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/ConnectivityExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/ForbiddenAuthExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/UnauthorizedUserExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/UnexpectedAuthExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/bootstrap/CertificateNotFoundExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/config/ForbiddenUserExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/config/NotFoundExceptionTest.java
> +    String expectedMessage = "\n" +
You could create a private method to build these String messages and avoid repeated code.

2017-06-23 14:54 UTC, campidelli commented on integration-commons/src/test/resources/application.yml
> +
Why is this file necessary?

2017-06-23 20:16 UTC, robson-sanchez requested changes

2017-06-23 20:16 UTC, robson-sanchez commented on integration-api-client/src/test/java/org/symphonyoss/integration/api/client/HttpApiClientDecoratorTest.java
> +    doReturn(CLIENT).when(apiClient).doGet(null, null, null, Client.class);
I think it's better to use mocked values instead of null.

2017-06-23 20:16 UTC, robson-sanchez commented on integration-api-client/src/test/java/org/symphonyoss/integration/api/client/SimpleHttpApiClientTest.java
> +    assertNotEquals(oldES, newES);
You might check if the new serializer is the same you have been set previously.

2017-06-23 21:21 UTC, aurojr commented on integration-commons/src/test/resources/application.yml
> +
This is used to test if the IntegrationProperties class is being correctly filled by String. I don't know if the test is useful, but the file is being used

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/config/NotFoundExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/config/ForbiddenUserExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/bootstrap/CertificateNotFoundExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/UnexpectedAuthExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/UnauthorizedUserExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/ForbiddenAuthExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/authentication/ConnectivityExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/RemoteApiExceptionTest.java
> +    String expectedMessage = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/MissingConfigurationExceptionTest.java
> +    String expected = "\n" +
Done!

2017-06-23 21:22 UTC, aurojr commented on integration-commons/src/test/java/org/symphonyoss/integration/exception/IntegrationRuntimeExceptionTest.java
> +        "Component: component\n" +
Done!

2017-06-26 12:02 UTC, crepache commented on integration-api-client/src/test/java/org/symphonyoss/integration/api/client/HttpApiClientDecoratorTest.java
> +    doReturn(CLIENT).when(apiClient).doGet(null, null, null, Client.class);
Done.

2017-06-26 12:14 UTC, crepache commented on integration-api-client/src/test/java/org/symphonyoss/integration/api/client/SimpleHttpApiClientTest.java
> +    assertNotEquals(oldES, newES);
Done.

2017-06-26 12:29 UTC, robson-sanchez approved these changes

2017-06-26 12:42 UTC, merged