APP-1215: Generic OAuth1.0 authorization done.
symphonyoss/App-Integrations-Commons pull request #97
Opened 2017-07-26 20:34 UTC by campidelli

New sub-project of Commons and generic OAuth1.0 structure done.

2017-07-27 16:33 UTC, robson-sanchez requested changes

2017-07-27 16:33 UTC, robson-sanchez commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/AuthorizationException.java
> +public abstract class AuthorizationException extends IntegrationRuntimeException {
Missing javadoc

2017-07-27 16:33 UTC, robson-sanchez commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/AuthorizationException.java
> +  public AuthorizationException(String message, Throwable cause, String... solutions) {
I believe we should move this class to 'integration-auth-commons' module.

See PR #98

2017-07-27 16:33 UTC, robson-sanchez commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/OAuthRsaSignerFactory.java
> +  private static PrivateKey getPrivateKey(String privateKey) {
We should move this method to a utility class because it will be used by other components.

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/v1/OAuth1Exception.java
> +public class OAuth1Exception extends AuthorizationException {
Missing javadoc

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/OAuthRsaSignerFactory.java
> +      throw new OAuth1Exception("'RSA' algorithm not found.", e,
We might move the exception message and solution to a bundle resource file.

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/v1/OAuth1Provider.java
> +      throw new OAuth1Exception("'Request temporary token' server url is invalid or unreachable.",
We might move the exception message and solution to a bundle resource file.

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/v1/OAuth1Provider.java
> +      throw new OAuth1Exception("'Request access token' server url is invalid or unreachable.",
We might move the exception message and solution to a bundle resource file.

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/src/main/resources/versioneye.properties
> +project_id=58efec9d4cedc5000f4ed5fd
We need to check with @ecarrenho-daitan how to generate a new project id.

2017-07-27 16:33 UTC, rsanchez-daitan commented on pom.xml
> +        <module>integration-authorization</module>
I believe all the code implemented here are related to OAuth1, so I suggest you rename to 'integration-oauth1'.

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/pom.xml
> +            <version>1.22.0</version>
Please create a new dependency entry on the dependency-management section on parent POM to avoid multiple versions of this dependency.

2017-07-27 16:33 UTC, rsanchez-daitan commented on integration-authorization/pom.xml
> +            <version>${commons.lang3.version}</version>
You can remove the version, once it's already defined in the parent pom.

2017-07-27 19:42 UTC, campidelli commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/AuthorizationException.java
> +  public AuthorizationException(String message, Throwable cause, String... solutions) {
As we have discussed, this will remain where it is for now.

2017-07-27 19:43 UTC, campidelli commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/OAuthRsaSignerFactory.java
> +  private static PrivateKey getPrivateKey(String privateKey) {
You are going to do that, right?

2017-07-27 20:12 UTC, campidelli commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/OAuthRsaSignerFactory.java
> +      throw new OAuth1Exception("'RSA' algorithm not found.", e,
Done.

2017-07-27 20:12 UTC, campidelli commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/v1/OAuth1Provider.java
> +      throw new OAuth1Exception("'Request temporary token' server url is invalid or unreachable.",
Done.

2017-07-27 20:12 UTC, campidelli commented on integration-authorization/src/main/java/org/symphonyoss/integration/authorization/oauth/v1/OAuth1Provider.java
> +      throw new OAuth1Exception("'Request access token' server url is invalid or unreachable.",
Done.

2017-07-27 20:12 UTC, campidelli commented on pom.xml
> +        <module>integration-authorization</module>
As we have discussed, this will remain where it is for now.

2017-07-28 12:58 UTC, robson-sanchez approved these changes

2017-07-28 13:02 UTC, merged